apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: saf-boot-starter-sample-allinone-service-prod
    inc-app: saf-boot-starter-sample-allinone-service
  name: saf-boot-starter-sample-allinone-service-prod
  namespace: inc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: saf-boot-starter-sample-allinone-service-prod
